### PR TITLE
Fix/israel contribution

### LINKED ISSUE #120: Remove the partner question
because we don't use it for anything.

Notes:
Remove from the form objects

### PR DESCRIPTION
**Pull request by dlouise64**
# What has changed and why?
fixes #120 #139 #138 #137 #143 #73 #75 
# How to test this change

- [ ] has automated tests
- [ ] at least one a reviewer ran the code
- [ ] tested in small screen
- [ ] i18n
- [ ] tested in screen reader/contrast <-- remove this if no UX change

### CODE REVIEW

File: src/components/App.js [hunk 1]
```diff
@@ -1,130 +1,118 @@
...
-  setName(el) {
-    if(el.name === 'gender') {
-      return this.state.setGender;
-    } else if(el.name === 'has_partner') {
-      return this.state.setPartner;
-    } else {
-      return el.value;
-    }
-  }
+    DATA['Uruguay'].persons.Tahi.gender['2018-01'] = this.state.gender;
```
Comment (Br3nda) [inline src/components/App.js]: Nice use of hash for statemachine

File: src/components/Madlib.js [hunk 2]
```diff
@@ -38,24 +38,22 @@ const Input = styled.input.attrs({ type: 'text' })`
...
+const MadLib = props => <MadLibWrapper>
+  {props.values && <div><Paragraph>I am a</Paragraph>
+    <Input readonly="readonly" defaultValue={props.values.age} />
     <Paragraph>year old</Paragraph>
-    <Input style={{ width: '130px' }} defaultValue={props.values.setGender} /><br />
+    <Input readonly="readonly" style={{ width: '130px' }} defaultValue={props.values.gender} /><br />
     {props.values.number_of_children > 0 && <Fragment>
       <Paragraph>who has had</Paragraph>
-      <Input defaultValue={props.values.number_of_children} />
+      <Input readonly="readonly" defaultValue={props.values.number_of_children} />
```
Comment (Br3nda) [inline src/components/Madlib.js]: :sparkles:

File: src/data/countries.js [hunk 3]
```diff
@@ -1,24 +1,42 @@
 const countries = [
   {
     name: 'New Zealand',
-    eligible: false,
-    age: 60,
-    hasCitizenship: true,
-    reqContributionYears: 30
+    label: 'new_zealand',
```
Comment (Br3nda) [inline src/data/countries.js]: SUPER VERY GOOD AWESOME
